### ISSUE TITLE
Css class is missing some places

### ISSUE THREAD

**Issue by alekoii** [Nickfis/svelte5-course-starter-templates#1]
Css class is missing on
the following components

https://github.com/Nickfis/svelte5-course-starter-templates/blob/main/ebook-landing/src/lib/components/ChapterPreview.svelte
```css
.chapter-preview {
	padding: 80px;
	margin-left: 12vw;
	margin-right: 20vw;
	max-width: 1150px;
}
```

https://github.com/Nickfis/svelte5-course-starter-templates/blob/main/ebook-landing/src/lib/components/AuthorSection.svelte
```css
.author-section {
	padding: 80px 0;
	margin-left: 12vw;
	margin-right: 20vw;
        max-width: 1150;
}
```
